date: 2019-08-05 15:15
app: markdown
layout: 'post'
title: 'Lustre故障跟踪之ldlm_resource_complain'
tags: Lustre

今天运维同事反馈过来一个问题，有个集群的客户端重启后无法挂载Lustre，报错信息如下：
```bash
[root@host-xx-xx-xx-xx ~]# mount.lustre -o localflock xx.xx.xx.202@o2ib:xx.xx.xx.201@o2ib:/shlfs /mnt/lustre/
mount.lustre: mount xx.xx.xx.202@o2ib:xx.xx.xx.201@o2ib:/shlfs at /mnt/lustre failed: Input/output error
Is the MGS running?
```
Lustre集群的信息如下：
- Lustre版本
    - 2.8.0
- 是否使用IB
    - Yes

客户端的dmesg信息如下所示：
```bash
[162983.746777] LustreError: 166-1: MGCxx.xx.xx.202@o2ib: Connection to MGS (at xx.xx.xx.202@o2ib) was lost; in progress operations using this service will fail
[162983.753239] LustreError: 28143:0:(ldlm_request.c:125:ldlm_expired_completion_wait()) ### lock timed out (enqueued at 1564973016, 300s ago), entering recovery for MGS@MGCxx.xx.xx.202@o2ib_0 ns: MGCxx.xx.xx.202@o2ib lock: ffff883e064a4400/0x460c6f21125734b1 lrc: 4/1,0 mode: --/CR res: [0x73666c6873:0x0:0x0].0x0 rrc: 1 type: PLN flags: 0x1000000000000 nid: local remote: 0xa68b3e19634974ca expref: -99 pid: 28143 timeout: 0 lvb_type: 0
[162983.753621] LustreError: 28218:0:(ldlm_resource.c:887:ldlm_resource_complain()) MGCxx.xx.xx.202@o2ib: namespace resource [0x73666c6873:0x0:0x0].0x0 (ffff8817ed040780) refcount nonzero (1) after lock cleanup; forcing cleanup.
[162983.753627] LustreError: 28218:0:(ldlm_resource.c:1502:ldlm_resource_dump()) --- Resource: [0x73666c6873:0x0:0x0].0x0 (ffff8817ed040780) refcount = 2
[162983.753631] LustreError: 28218:0:(ldlm_resource.c:1523:ldlm_resource_dump()) Waiting locks:
[162983.753640] LustreError: 28218:0:(ldlm_resource.c:1525:ldlm_resource_dump()) ### ### ns: MGCxx.xx.xx.202@o2ib lock: ffff883e064a4400/0x460c6f21125734b1 lrc: 4/1,0 mode: --/CR res: [0x73666c6873:0x0:0x0].0x0 rrc: 2 type: PLN flags: 0x1106400000000 nid: local remote: 0xa68b3e19634974ca expref: -99 pid: 28143 timeout: 0 lvb_type: 0
[162983.753644] LustreError: 28218:0:(ldlm_resource.c:1525:ldlm_resource_dump()) Skipped 1 previous similar message
[162983.753662] Lustre: MGCxx.xx.xx.202@o2ib: Connection restored to MGCxx.xx.xx.202@o2ib_0 (at xx.xx.xx.202@o2ib)
[163284.097045] LustreError: 15c-8: MGCxx.xx.xx.202@o2ib: The configuration from log 'shlfs-client' failed (-5). This may be the result of communication errors between this node and the MGS, a bad configuration, or other errors. See the syslog for more information.
[163284.106850] Lustre: Unmounted shlfs-client
[163284.107516] LustreError: 28143:0:(obd_mount.c:1426:lustre_fill_super()) Unable to mount  (-5)
```

从客户端的日志中有一条日志特别突出：
```bash
[162983.753621] LustreError: 28218:0:(ldlm_resource.c:887:ldlm_resource_complain()) MGCxx.xx.xx.202@o2ib: namespace resource [0x73666c6873:0x0:0x0].0x0 (ffff8817ed040780) refcount nonzero (1) after lock cleanup; forcing cleanup.
[162983.753627] LustreError: 28218:0:(ldlm_resource.c:1502:ldlm_resource_dump()) --- Resource: [0x73666c6873:0x0:0x0].0x0 (ffff8817ed040780) refcount = 2
```
为什么这里的引用计数不是0？

